service: node-aws-lambda-graphql-example-todo

plugins:
  - serverless-domain-manager
  - serverless-aws-documentation
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  profile: serverless
  stage: dev
  region: us-east-1

  logs:
    restApi: true

  tracing:
    apiGateway: true
    lambda: true

  environment:
    DEBUG: ${self:custom.environment.debugLog}
    NODE_ENV: ${self:custom.environment.nodeEnvironment}

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}

  domainName: ${self:custom.domainNameStage.${self:custom.stage}}
  domainNameStage:
    dev: dev-api.${self:custom.baseDomainName}
    test: test-api.${self:custom.baseDomainName}
    prod: api.${self:custom.baseDomainName}
  baseDomainName: codesaplings.com
  customDomain:
    domainName: ${self:custom.domainName}
    certificateName: ${self:custom.domainName}
    basePath: todo
    stage: ${self:custom.stage}
    createRoute53Record: true
  environment:
    debugLog: ${self:custom.environment.debugLogStage.${self:custom.stage}}
    debugLogStage:
      dev: ''
      test: ''
      prod: ''
    nodeEnvironment: ${self:custom.environment.nodeEnvironmentStage.${self:custom.stage}}
    nodeEnvironmentStage:
      dev: development
      test: test
      prod: production

  documentation:
    info:
      title: node-aws-lambda-graphql-example-todo
      description: GraphQL Todo Example
      version: 1.0.0

package:
  individually: false

  exclude:
    - .circleci/**
    - .idea/**
    - .env*
    - examples/**
    - scripts/**
    - spec/**
    - tmp/**
    - '**/node_modules/aws-sdk/**'

functions:
  graphql:
    handler: dist/events/apollo.handler
    events:
      - http:
          path: graphql
          method: get
          cors: true
          documentation:
            summary: GraphQL Server
            description: GraphQL Server

      - http:
          path: graphql
          method: post
          cors: true
          documentation:
            summary: GraphQL Server
            description: GraphQL Server
